export const ON_LOGIN_START = 'ON_LOGIN_START';
export const ON_LOGIN_SUCCESS = 'ON_LOGIN_SUCCESS';
export const ON_LOGIN_FAILURE = 'ON_LOGIN_FAILURE';

export const ON_REGISTER_START = 'ON_REGISTER_START';
export const ON_REGISTER_SUCCESS = 'ON_REGISTER_SUCCESS';
export const ON_REGISTER_FAILURE = 'ON_REGISTER_FAILURE';

export const ON_GOOGLE_AUTH_START = 'ON_GOOGLE_AUTH_START';
export const ON_GOOGLE_AUTH_SUCCESS = 'ON_GOOGLE_AUTH_SUCCESS';
export const ON_GOOGLE_AUTH_FAILURE = 'ON_GOOGLE_AUTH_FAILURE';

export const ON_LOGOUT_START = 'ON_LOGOUT_START';
export const ON_LOGOUT_SUCCESS = 'ON_LOGOUT_SUCCESS';
